name: operation check

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Make calculator executable
      run: chmod +x ./calculator

    - name: Run Python Script with input
      run: |
        echo -e "c10\n+\nc5\n=" | calculator
        echo -e "fs30\n+\nfq25\n=" | calculator
        echo -e "fp2,6\n*\nfl3,27\n=" | calculator
